import {test} from 'node:test';import assert from 'node:assert/strict';import {analyze,LIMITS} from '../lib/index.js';
let seed=20260930;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};
function value(depth=0){const n=Math.floor(rnd()*(depth>3?5:7));switch(n){case 0:return null;case 1:return rnd()>.5;case 2:return (rnd()-.5)*1e25;case 3:return ['a/b~c','😀','\\"\n','__proto__','\ud800'][Math.floor(rnd()*5)];case 4:return Math.floor(rnd()*10000);case 5:return Array.from({length:Math.floor(rnd()*5)},()=>value(depth+1));default:return Object.fromEntries(Array.from({length:Math.floor(rnd()*5)},(_,i)=>['key'+i,value(depth+1)]));}}
const native=s=>{try{JSON.parse(s);return true;}catch{return false;}};
test('1,000 generated valid inputs and 3,000 mutations match native acceptance',()=>{for(let i=0;i<1000;i++){const s=JSON.stringify(value(),null,i%2?2:0);assert.equal(analyze(s).valid,true,s);for(const t of [s.slice(0,-1),s+'x',s.slice(0,s.length>>1)+','+s.slice(s.length>>1)])assert.equal(analyze(t).valid,native(t),JSON.stringify(t));}});
test('negative underflow is underflow, not intentional negative zero',()=>{assert.equal(analyze('-1e-400').findings[0].code,'underflow');assert.equal(analyze('-0e-400').findings[0].code,'negative-zero');});
test('multi-duplicate IDs unique and escaped keys decoded',()=>{const r=analyze('{"a":{"x":1,"x":2},"a":{"x":3,"x":4},"a":{"x":5,"x":6}}');assert.equal(r.stats.duplicates,5);assert.equal(new Set(r.findings.map(f=>f.id)).size,5);});
test('entries and token budgets fail cleanly',()=>{assert.equal(analyze('['+Array(LIMITS.entries+1).fill('1').join(',')+']').error.code,'limit-entries');const s='{'+Array(LIMITS.entries).fill('"a":1').join(',')+'}';assert.equal(analyze(s).error.code,'limit-tokens');});
test('large valid number and string avoid unbounded numeric expansion',()=>{const r=analyze('0.'+'0'.repeat(4000)+'1');assert.equal(r.valid,true);assert.equal(r.findings[0].code,'underflow');assert.equal(analyze(JSON.stringify('a'.repeat(500000))).valid,true);});
