import {analyze, renderHtmlReport, createReproducer, DEMO_SOURCE, LIMITS, type Report, type Severity} from '../src/index.js';
import './style.css';
const root=document.querySelector<HTMLDivElement>('#app')!;
root.innerHTML=`<header class="topbar"><a class="brand" href="#workspace" aria-label="JSONCliff workspace"><span class="logo" aria-hidden="true">{↳}</span>JSONCliff<span class="version">v0.1</span></a><div class="private-label"><span aria-hidden="true">◈</span> Local processing. No uploads.</div></header>
<main id="workspace"><section class="intro"><div><p class="eyebrow">JSON → JAVASCRIPT → JSON</p><h1>Spot the silent changes<span>.</span></h1><p class="lede">See exactly what <code>JSON.parse</code> and <code>JSON.stringify</code> leave behind.</p></div><div class="intro-note"><strong>Numbers. Duplicates. Evidence.</strong><span>Paste the original response, before JavaScript parses it.</span></div></section>
<section class="toolbar" aria-label="Analysis controls"><div class="samples"><span class="toolbar-label">Try a case</span><button data-sample="demo" class="sample active">API response</button><button data-sample="boundaries" class="sample">Number edges</button><button data-sample="clean" class="sample">Clean JSON</button></div><div class="input-actions"><label class="file-button" for="file">Open .json<input id="file" type="file" accept=".json,application/json,text/plain"></label><button id="clear" class="subtle">Clear</button><button id="analyze" class="primary">Analyze <kbd>⌘ / Ctrl ↵</kbd></button></div></section>
<div id="status" role="status" aria-live="polite" class="status"></div>
<section class="editors" aria-label="Round-trip comparison"><article class="editor"><div class="panel-heading"><label for="source"><span class="step">01</span>Original JSON</label><span id="input-meta" class="meta">UTF-8 · max 1 MiB</span></div><textarea id="source" spellcheck="false" autocomplete="off" autocapitalize="off" aria-describedby="source-help" placeholder='Paste JSON here, e.g. {"id":9007199254740993}'></textarea><div class="panel-foot"><span id="source-help">Exact source spelling is preserved</span><span id="cursor">Ready</span></div></article><article class="editor output-panel"><div class="panel-heading"><label for="output"><span class="step">02</span>Native round-trip output</label><span class="engine-label">JavaScript Number</span></div><textarea id="output" readonly spellcheck="false" aria-describedby="output-help" placeholder="Analyze JSON to see the native output"></textarea><div class="panel-foot"><span id="output-help">JSON.stringify(JSON.parse(source), null, 2)</span><span>Read only</span></div></article></section>
<section class="evidence"><div class="evidence-header"><div><p class="eyebrow">SOURCE-LINKED DIAGNOSTICS</p><h2>Follow the evidence <span id="total" class="count">0</span></h2></div><div class="filters" role="group" aria-label="Filter findings"><button data-filter="all" aria-pressed="true">All <span id="all-count">0</span></button><button data-filter="change" aria-pressed="false">Changes <span id="change-count">0</span></button><button data-filter="risk" aria-pressed="false">Risks <span id="risk-count">0</span></button><button data-filter="info" aria-pressed="false">Spelling <span id="info-count">0</span></button></div></div><p class="evidence-hint">Select a finding to highlight its original source. “Spelling” means the decimal value is unchanged.</p><div id="findings" class="findings"></div></section>
<section class="exports" aria-label="Export diagnostics"><div><strong>Take the evidence with you</strong><p>Exports include the original input. Check for secrets before sharing.</p></div><div><button id="download-json">Diagnostic JSON</button><button id="download-html">HTML report</button><button id="download-repro">Runnable .mjs</button></div></section>
<footer><p><strong>No persistence, no telemetry.</strong> Your input stays in this tab. The app works offline after loading.</p><p>This compares decimal values across a native round trip. It doesn’t flag ordinary <code>0.1</code> as corrupted or silently “fix” your data.</p><details><summary>Limits &amp; interpretation</summary><p>Strict JSON only: no comments, trailing commas, NaN, or Infinity literals. File imports must be valid UTF-8. Maximum: 1 MiB, 60,000 tokens, 20,000 entries, depth 128, 4,096 characters per number. Source locations use one-based lines and UTF-16 columns; spans are zero-based and end-exclusive.</p><p>Duplicate-key findings identify overwritten occurrences. Nested numbers in discarded properties aren’t counted again. Unsafe but preserved integers are risks, not value changes. String escaping, whitespace, and object-key order aren’t reported. A replacement preview for duplicate keys shows its original source spelling.</p></details><span class="footer-mark">JSONCliff / inspect before you trust</span></footer></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const source=$<HTMLTextAreaElement>('#source'),output=$<HTMLTextAreaElement>('#output'),status=$('#status'),findings=$('#findings');
let report:Report|null=null,filter:'all'|Severity='all',selected='',revision=0,page=0;
const samples:Record<string,string>={demo:DEMO_SOURCE,boundaries:'{\n  "safe": 9007199254740991,\n  "unsafeButPreserved": 9007199254740992,\n  "rounded": 9007199254740993,\n  "underflow": -1e-400,\n  "formatOnly": 1.2300,\n  "ordinary": 0.1\n}',clean:'{\n  "id": "9007199254740993",\n  "status": "paid",\n  "amount": 12.5,\n  "items": [1, 2, 3],\n  "active": true\n}'};
const exportButtons=['#download-json','#download-html','#download-repro'].map(x=>$<HTMLButtonElement>(x));
function message(text:string,kind=''){status.textContent=text;status.className='status '+kind;}
function node(tag:string,text:string,cls=''){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function cursor(){const before=source.value.slice(0,source.selectionStart),line=before.split('\n');$('#cursor').textContent=`Ln ${line.length}, Col ${line.at(-1)!.length+1}`;}
function render(){
 findings.replaceChildren();const fs=report?.findings||[];
 $('#total').textContent=String(fs.length);$('#all-count').textContent=String(fs.length);
 for(const severity of ['change','risk','info'])$('#'+severity+'-count').textContent=String(fs.filter(f=>f.severity===severity).length);
 document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));
 const visible=fs.filter(f=>filter==='all'||f.severity===filter);
 if(!visible.length){const box=node('div','', 'empty');box.append(node('strong',!report?'Waiting for your JSON':!report.valid?'Analysis paused':fs.length?'No findings in this category':'No observed changes'),node('p',!report?'Paste or open JSON, then analyze.':!report.valid?'Fix the input error above to continue.':fs.length?'Try another filter to inspect the other findings.':'The numeric values and property occurrences survive this round trip.'));findings.append(box);return;}
 for(const f of visible.slice(page*100,(page+1)*100)){
  const card=document.createElement('button');card.type='button';card.className='finding '+f.severity+(selected===f.id?' selected':'');card.setAttribute('aria-label',`${f.title}, ${f.pointer||'root'}, line ${f.line}`);card.setAttribute('aria-pressed',String(selected===f.id));
  const top=node('div','', 'finding-top');top.append(node('span',f.severity==='info'?'SPELLING':f.severity.toUpperCase(),'badge'),node('span',`L${f.line}:${f.column}`,'location'));
  const vals=node('div','', 'value-diff');vals.append(node('code',f.before,'before'),node('span','→','diff-arrow'),node('code',f.after??'—','after'));
  card.append(top,node('h3',f.title),node('p',(f.pointer||'(root)')+` · occurrence ${f.occurrence}`,'pointer'),vals,node('p',f.message,'explanation'));
  card.addEventListener('click',()=>{selected=f.id;render();source.focus();source.setSelectionRange(f.start,f.end);const lineHeight=parseFloat(getComputedStyle(source).lineHeight)||25;source.scrollTop=Math.max(0,(f.line-3)*lineHeight);cursor();});findings.append(card);
 }
 if(visible.length>100){const nav=node('div','', 'finding-nav');const prev=document.createElement('button'),next=document.createElement('button');prev.textContent='Previous 100';next.textContent='Next 100';prev.disabled=page===0;next.disabled=(page+1)*100>=visible.length;prev.onclick=()=>{page--;render();};next.onclick=()=>{page++;render();};nav.append(prev,node('span',`${page*100+1}–${Math.min((page+1)*100,visible.length)} of ${visible.length} · exports contain all findings`),next);findings.append(nav);}
}
function markDirty(){revision++;report=null;selected='';page=0;output.value='';exportButtons.forEach(b=>b.disabled=true);message('Input changed. Analyze to refresh the evidence.','pending');$('#input-meta').textContent=`${(source.value.length>LIMITS.bytes?'over 1 MiB':new TextEncoder().encode(source.value).length.toLocaleString())} bytes · UTF-8`;document.querySelectorAll('.sample').forEach(b=>b.classList.remove('active'));render();}
function run(){
 revision++;selected='';page=0;report=analyze(source.value);output.value=report.output||'';$('#input-meta').textContent=`${report.stats.bytes.toLocaleString()} bytes · ${report.stats.tokens.toLocaleString()} tokens`;
 exportButtons[0].disabled=false;exportButtons[1].disabled=false;exportButtons[2].disabled=!report.valid;
 if(report.valid){const c=report.findings.filter(f=>f.severity==='change').length,r=report.findings.filter(f=>f.severity==='risk').length;message(c?`${c} material changes found. The native round trip changes or discards data.`:r?`No material changes. ${r} integer risk${r===1?'':'s'} worth reviewing.`:'No material changes found in this round trip.',c?'changed':r?'warning':'clean');}
 else {message(`${report.error!.message} Line ${report.error!.line}, column ${report.error!.column}.`,'error');source.focus();source.setSelectionRange(report.error!.start,report.error!.end);}
 render();cursor();
}
function save(filename:string,type:string,text:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#analyze').addEventListener('click',run);source.addEventListener('input',markDirty);source.addEventListener('keyup',cursor);source.addEventListener('click',cursor);source.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run();}});
$('#clear').addEventListener('click',()=>{source.value='';markDirty();message('Paste or open JSON to begin.');source.focus();});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-sample]'))b.addEventListener('click',()=>{source.value=samples[b.dataset.sample!];run();document.querySelectorAll('.sample').forEach(el=>el.classList.toggle('active',el===b));});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-filter]'))b.addEventListener('click',()=>{filter=b.dataset.filter as typeof filter;page=0;render();});
$('#file').addEventListener('change',async e=>{const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;const rev=++revision;try{if(file.size>LIMITS.bytes)throw Error('File exceeds the 1 MiB limit.');const bytes=await file.arrayBuffer();if(rev!==revision)return;let value;try{value=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(bytes);}catch{throw Error('File is not valid UTF-8. Convert it to UTF-8 and try again.');}source.value=value;run();document.querySelectorAll('.sample').forEach(b=>b.classList.remove('active'));}catch(error){if(rev===revision)message(error instanceof Error?error.message:String(error),'error');}finally{input.value='';}});
$('#download-json').addEventListener('click',()=>{if(report)save('jsoncliff-report.json','application/json',JSON.stringify(report,null,2));});
$('#download-html').addEventListener('click',()=>{if(report)save('jsoncliff-report.html','text/html',renderHtmlReport(report));});
$('#download-repro').addEventListener('click',()=>{if(report?.valid)save('reproduce.mjs','text/javascript',createReproducer(report.source));});
source.value=DEMO_SOURCE;run();
